import Head from 'next/head';
import Image from 'next/image';
// import TheNavbar from "../components/TheNavbar";
import classes from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={classes.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/*<TheNavbar />*/}
      <main className={classes.main}>
       <p id='test' className={classes.test}>test</p>




      </main>

      <footer className={classes.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={classes.logo}>
            <Image src="/img/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
